### ISSUE TITLE
"haskell-cafe" google groups is unmoderated spam

### ISSUE THREAD

**Issue by chreekat** [haskellnews/haskellnews#51]
I've determined anecdotally that the only "real" haskell-cafe is only the one you sign up for at https://mail.haskell.org/mailman/listinfo/haskell-cafe. The google group is apparently derelict.

I imagine getting haskellnews to import from a mailing list is not as nice as pulling a feed, but I'd suggest perhaps just ditching the feed in the meanwhile.

**Comment by lwm** [comment]
Ah, I see. Yes, it is just job postings and so on ... not good. I think parsing the mailman list was attempted in https://github.com/chrisdone/haskellnews/pull/14 but was abandoned. I Do you feel like following with a PR based on the work of that PR? As for ditching the feed, you're probably right.

**Comment by chreekat** [comment]
Cool that someone has already taken a stab at it. Unfortunately I know that I personally won't be able to spend any time on adding/supporting the feature. :/

**Comment by beerendlauwers** [comment]
PR is in the works: https://github.com/haskellnews/haskellnews/pull/53
