### ISSUE TITLE
Move haskellnews to DigitalOcean

### ISSUE THREAD

**Issue by chrisdone** [haskellnews/haskellnews#52]
Most of my services are all running on an old dedicated server. I've started the process of moving them onto individual DigitalOcean droplets. I'll move haskellnews next.

@lwm Once I've done that, I'd like to create a "Team" on DigitalOcean in which me, you and others have access in order to do deploys, maintenance, etc. on the machine. (Or otherwise add public keys for SSH login). What do you think about that? I'm not using Haskell News as much as I was in the past, but it has its own userbase and doesn't need much development. I think if we made it more "community" managed that would make me more redundant.

**Comment by lwm** [comment]
> What do you think about that?

Sounds great! I agree with what you said. The more the merrier :+1:

**Comment by chrisdone** [comment]
Okay, I've setup a copy of haskelnews here: http://104.236.226.61/

I've updated the DNS records, but it might take a day or so to propagate across the intertubes.

I'm looking into DigitalOcean groups now.

**Comment by chrisdone** [comment]
@lwm I've added you as a member of the "Haskell News" team. If you accept that, you can login to DO and switch to that team:

<img width="284" alt="screenshot 2017-02-01 21 40 58" src="https://cloud.githubusercontent.com/assets/11019/22527444/2c35d9d6-e8c7-11e6-9b6a-680dc7bfadf6.png">

Load up the haskellnews droplet:

<img width="658" alt="screenshot 2017-02-01 21 41 46" src="https://cloud.githubusercontent.com/assets/11019/22527471/46076ae6-e8c7-11e6-8b4c-0960104fd93f.png">

From there you can see all the information.

Please email me your public key and I'll add you to `.ssh/authorized_keys` and you can SSH into the machine.

**Comment by lwm** [comment]
Nice! I'll get on this now.

**Comment by chrisdone** [comment]
I've created a haskellnews GitHub organization, and I've invited me and you as owners of the organization. I've transferred this repo to that organization.

This should scale more easily. People we trust can be added to the GitHub organization, and people we really trust can be added to the DigitalOcean team. :metal:

**Comment by lwm** [comment]
This is all very cool. :beers:

**Comment by chrisdone** [comment]
@lwm Great, added your public key! It's a `root` login, but the server itself runs under the username `haskellnews`. You can see it in the root login with `screen -x`. The binary and `static/` content and config is all under `/opt`. Nothing fancy. The default nginx reverse proxies to haskellnews's server.

Feel free to extend or reconfigure, e.g. for a more automated deploy. There is a snapshot which is a back-up of this working version, worst-case scenario we just restore the snapshot.

**Comment by lwm** [comment]
Great! Yes, I feel more motivated to come back to hack on this now :) 

Looks like you can close this one off then. Nice job. :rainbow:

**Comment by chrisdone** [comment]
Awesome! Let me know if you need anything else. 👍
