### ISSUE TITLE
update http://haskellnews.org/ ?

### ISSUE THREAD

**Issue by jwaldmann** [haskellnews/haskellnews#56]
What's holding back the roll-out of recent improvements? 

In particular, the mailman parser for haskell-cafe? And it would work for other mailman lists as well.

I am still seeing google-group spam in the top right pane at http://haskellnews.org/grouped .

--

PS: Don't wait too long - mailing lists will die. As usenet did. Cf. [comp.lang.functional](http://www.cs.nott.ac.uk/~pszgmh/faq.html). What's that usenet thing, anyway? [Not a google group](https://web-beta.archive.org/web/20080513070004/http://improve-usenet.org/underlying.html).

**Comment by lwm** [comment]
Getting on this now!

**Comment by lwm** [comment]
Updated! Thanks for following up @jwaldmann! If you'd be interested in helping maintain the project, it's a community effort and we'd be happy to have you. Just let me know and I can add you to the organisation.

**Comment by jwaldmann** [comment]
I see the update is working, nice.  

Still, this feels like trying to "repair the internet", see https://xkcd.com/386/ . I don't have too much time for this. This mailman patch was just to 

* exemplify how to walk a DOM (I might use this in teaching), 
* fight the concept that Google owns everything (but -  see start of this comment).
