### ISSUE TITLE
Travis build is not failing when it should

### ISSUE THREAD

**Issue by decentral1se** [haskellnews/haskellnews#62]
On the build for https://github.com/haskellnews/haskellnews/pull/61, I saw:

https://travis-ci.org/haskellnews/haskellnews/builds/216280502#L309

This is unrelated to #61 but should be fixed.

**Comment by lwm** [comment]
We should probably increase the sleep on https://travis-ci.org/haskellnews/haskellnews/builds/216280502#L316 as well. Not sure if it is killed before it has successfully curl'd the endpoint.
