### ISSUE TITLE
libpq: failed (no connection to the server

### ISSUE THREAD

**Issue by igrep** [haskellnews/haskellnews#64]
Is http://haskellnews.org/ currently down?
I get an error below since this morning...

```
A web handler threw an exception. Details:
libpq: failed (no connection to the server
)
```

**Comment by lwm** [comment]
ooooh, looks bad. On holidays at he moment but will try and get a look at it soon. Thanks for the report!

**Comment by igrep** [comment]
Confirmed fixed!
