### ISSUE TITLE
Planet Haskell's newest post is 12 months in the future

### ISSUE THREAD

**Issue by Lysxia** [haskellnews/haskellnews#66]
![sc-2018-01-02t03 20 07-05 00](https://user-images.githubusercontent.com/2515201/34477967-f0e0abc0-ef6b-11e7-92a1-68bb5bc7b42d.png)

The actual date of the post is 2017-12-14. It would be less annoying if the post didn't remain at the top.

**Comment by kodaj** [comment]
FYI, the problem is still present as of February 8, 2018 (more than 1 month after this issue was opened). I do realize this is not a high-priority bug, but still, it's sort of an ugly wart on a fairly visible surface, so if someone had time to take a look, I think that would be great.
