### ISSUE TITLE
PINNED: Co-Maintainers wanted! Commit bits here!

### ISSUE THREAD

**Issue by decentral1se** [haskellnews/haskellnews#70]
As noted in https://github.com/haskellnews/haskellnews/issues/65#issuecomment-365112572, co-maintainers are needed! 

Please weigh in here and let's see what we can do!

**Comment by sboosali** [comment]
Can you provide some context about  what's involved? Like, do you just want someone to help add text files each week (which i could do that :)? Or also fixing the server if something's wrong, developing new features, etc?

**Comment by decentral1se** [comment]
So, the current situation is: @chrisdone invited myself to help maintain as he did not have time. I briefly was able to make some improvements but am running out of time myself these days.

What would be required to be a maintainer: I think it would just be this:

  1) Review and merge PRs
  2) Triage issues
  3) Decide on releases and tag them

I'll handle the deployments for now. We can spread that out after then.

So, basic stuff folks! Please comment here and I will create a team with permissions.
